The dataset contains 36733 instances of 11 sensor measures aggregated over one hour (by means of average or sum) from a gas turbine. 
The Dataset includes gas turbine parameters (such as Turbine Inlet Temperature and Compressor Discharge pressure) in addition to the ambient variables.



Problem statement: predicting turbine energy yield (TEY) using ambient variables as features.



Attribute Information:

The explanations of sensor measurements and their brief statistics are given below.

Variable (Abbr.) Unit Min Max Mean

Ambient temperature (AT) C –6.23 37.10 17.71

Ambient pressure (AP) mbar 985.85 1036.56 1013.07

Ambient humidity (AH) (%) 24.08 100.20 77.87

Air filter difference pressure (AFDP) mbar 2.09 7.61 3.93

Gas turbine exhaust pressure (GTEP) mbar 17.70 40.72 25.56

Turbine inlet temperature (TIT) C 1000.85 1100.89 1081.43

Turbine after temperature (TAT) C 511.04 550.61 546.16

Compressor discharge pressure (CDP) mbar 9.85 15.16 12.06

Turbine energy yield (TEY) MWH 100.02 179.50 133.51

Carbon monoxide (CO) mg/m3 0.00 44.10 2.37

Nitrogen oxides (NOx) mg/m3 25.90 119.91 65.29

In [1]:
# Importing the necessary packages
import pandas as pd
import numpy as np
import keras
import tensorflow
from sklearn.preprocessing import StandardScaler

In [62]:
# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

# Keras specific
import keras
from keras.models import Sequential
from keras.layers import Dense

In [2]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [4]:
data = pd.read_csv("gas_turbines.csv")

In [5]:
data.head()

AT      AP      AH    AFDP    GTEP     TIT     TAT     TEY     CDP  \
0  6.8594  1007.9  96.799  3.5000  19.663  1059.2  550.00  114.70  10.605   
1  6.7850  1008.4  97.118  3.4998  19.728  1059.3  550.00  114.72  10.598   
2  6.8977  1008.8  95.939  3.4824  19.779  1059.4  549.87  114.71  10.601   
3  7.0569  1009.2  95.249  3.4805  19.792  1059.6  549.99  114.72  10.606   
4  7.3978  1009.7  95.150  3.4976  19.765  1059.7  549.98  114.72  10.612   

       CO     NOX  
0  3.1547  82.722  
1  3.2363  82.776  
2  3.2012  82.468  
3  3.1923  82.670  
4  3.2484  82.311

In [15]:
data[['TEY1']] = data[['TEY']]

In [16]:
data.head()

AT      AP      AH    AFDP    GTEP     TIT     TAT     TEY     CDP  \
0  6.8594  1007.9  96.799  3.5000  19.663  1059.2  550.00  114.70  10.605   
1  6.7850  1008.4  97.118  3.4998  19.728  1059.3  550.00  114.72  10.598   
2  6.8977  1008.8  95.939  3.4824  19.779  1059.4  549.87  114.71  10.601   
3  7.0569  1009.2  95.249  3.4805  19.792  1059.6  549.99  114.72  10.606   
4  7.3978  1009.7  95.150  3.4976  19.765  1059.7  549.98  114.72  10.612   

       CO     NOX       y    TEY1  
0  3.1547  82.722  114.70  114.70  
1  3.2363  82.776  114.72  114.72  
2  3.2012  82.468  114.71  114.71  
3  3.1923  82.670  114.72  114.72  
4  3.2484  82.311  114.72  114.72

In [19]:
data.drop(['y'], axis='columns', inplace=True)

In [20]:
data.head()

AT      AP      AH    AFDP    GTEP     TIT     TAT     TEY     CDP  \
0  6.8594  1007.9  96.799  3.5000  19.663  1059.2  550.00  114.70  10.605   
1  6.7850  1008.4  97.118  3.4998  19.728  1059.3  550.00  114.72  10.598   
2  6.8977  1008.8  95.939  3.4824  19.779  1059.4  549.87  114.71  10.601   
3  7.0569  1009.2  95.249  3.4805  19.792  1059.6  549.99  114.72  10.606   
4  7.3978  1009.7  95.150  3.4976  19.765  1059.7  549.98  114.72  10.612   

       CO     NOX    TEY1  
0  3.1547  82.722  114.70  
1  3.2363  82.776  114.72  
2  3.2012  82.468  114.71  
3  3.1923  82.670  114.72  
4  3.2484  82.311  114.72

In [21]:
data.drop(['TEY'], axis='columns', inplace=True)

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15039 entries, 0 to 15038
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AT      15039 non-null  float64
 1   AP      15039 non-null  float64
 2   AH      15039 non-null  float64
 3   AFDP    15039 non-null  float64
 4   GTEP    15039 non-null  float64
 5   TIT     15039 non-null  float64
 6   TAT     15039 non-null  float64
 7   CDP     15039 non-null  float64
 8   CO      15039 non-null  float64
 9   NOX     15039 non-null  float64
 10  TEY1    15039 non-null  float64
dtypes: float64(11)
memory usage: 1.3 MB


In [24]:
data.shape

(15039, 11)

In [25]:
data.describe()

AT           AP            AH          AFDP          GTEP  \
count  15039.000000  15039.00000  15039.000000  15039.000000  15039.000000   
mean      17.764381   1013.19924     79.124174      4.200294     25.419061   
std        7.574323      6.41076     13.793439      0.760197      4.173916   
min        0.522300    985.85000     30.344000      2.087400     17.878000   
25%       11.408000   1008.90000     69.750000      3.723900     23.294000   
50%       18.186000   1012.80000     82.266000      4.186200     25.082000   
75%       23.862500   1016.90000     90.043500      4.550900     27.184000   
max       34.929000   1034.20000    100.200000      7.610600     37.402000   

                TIT           TAT           CDP            CO           NOX  \
count  15039.000000  15039.000000  15039.000000  15039.000000  15039.000000   
mean    1083.798770    545.396183     12.102353      1.972499     68.190934   
std       16.527806      7.866803      1.103196      2.222206     10.470586   
min     1000.800000    512.450000      9.904400      0.000388     27.765000   
25%     1079.600000    542.170000     11.622000      0.858055     61.303500   
50%     1088.700000    549.890000     12.025000      1.390200     66.601000   
75%     1096.000000    550.060000     12.578000      2.160400     73.935500   
max     1100.800000    550.610000     15.081000     44.103000    119.890000   

               TEY1  
count  15039.000000  
mean     134.188464  
std       15.829717  
min      100.170000  
25%      127.985000  
50%      133.780000  
75%      140.895000  
max      174.610000

In [56]:
dataset= data.values
X = dataset[:,0:10]
y = dataset[:,-1]

In [57]:
X


array([[   6.8594, 1007.9   ,   96.799 , ...,   10.605 ,    3.1547,
          82.722 ],
       [   6.785 , 1008.4   ,   97.118 , ...,   10.598 ,    3.2363,
          82.776 ],
       [   6.8977, 1008.8   ,   95.939 , ...,   10.601 ,    3.2012,
          82.468 ],
       ...,
       [   7.2647, 1006.3   ,   99.496 , ...,   10.483 ,    7.9632,
          90.912 ],
       [   7.006 , 1006.8   ,   99.008 , ...,   10.533 ,    6.2494,
          93.227 ],
       [   6.9279, 1007.2   ,   97.533 , ...,   10.583 ,    4.9816,
          92.498 ]])

In [58]:
Y

array([114.7 , 114.72, 114.71, ..., 110.19, 110.74, 111.58])

In [59]:
# Standardization
a = StandardScaler()
a.fit(X)
X_standardized = a.transform(X)

In [60]:
pd.DataFrame(X_standardized).describe()

0             1             2             3             4  \
count  1.503900e+04  1.503900e+04  1.503900e+04  1.503900e+04  1.503900e+04   
mean  -1.169680e-15 -1.925280e-14  2.007245e-16  3.810001e-16  1.111478e-16   
std    1.000033e+00  1.000033e+00  1.000033e+00  1.000033e+00  1.000033e+00   
min   -2.276462e+00 -4.266288e+00 -3.536594e+00 -2.779497e+00 -1.806771e+00   
25%   -8.392292e-01 -6.706510e-01 -6.796337e-01 -6.266930e-01 -5.091458e-01   
50%    5.566605e-02 -6.227861e-02  2.277844e-01 -1.854065e-02 -8.075681e-02   
75%    8.051309e-01  5.772924e-01  7.916582e-01  4.612196e-01  4.228638e-01   
max    2.266234e+00  3.275970e+00  1.528011e+00  4.486233e+00  2.871006e+00   

                  5             6             7             8             9  
count  1.503900e+04  1.503900e+04  1.503900e+04  1.503900e+04  1.503900e+04  
mean  -2.324212e-15  1.744899e-15  2.542166e-16  1.959261e-17 -3.646853e-17  
std    1.000033e+00  1.000033e+00  1.000033e+00  1.000033e+00  1.000033e+00  
min   -5.021933e+00 -4.188141e+00 -1.992416e+00 -8.874862e-01 -3.861033e+00  
25%   -2.540512e-01 -4.101146e-01 -4.354335e-01 -5.015202e-01 -6.578107e-01  
50%    2.965544e-01  5.712570e-01 -7.011925e-02 -2.620452e-01 -1.518527e-01  
75%    7.382490e-01  5.928675e-01  4.311680e-01  8.455882e-02  5.486567e-01  
max    1.028678e+00  6.627839e-01  2.700105e+00  1.895949e+01  4.937717e+00

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)
print(X_train.shape); print(X_test.shape)

(10527, 10)
(4512, 10)


In [64]:
# Define model
model = Sequential()
model.add(Dense(500, input_dim=10, activation= "relu"))
model.add(Dense(100, activation= "relu"))
model.add(Dense(50, activation= "relu"))
model.add(Dense(1))
#model.summary() #Print model Summary

In [65]:
model.compile(loss= "mean_squared_error" , optimizer="adam", metrics=["mean_squared_error"])
model.fit(X_train, y_train, epochs=20)

Epoch 1/20
329/329 [==============================] - 1s 2ms/step - loss: 272.7357 - mean_squared_error: 272.7357
Epoch 2/20
329/329 [==============================] - 1s 2ms/step - loss: 17.0893 - mean_squared_error: 17.0893
Epoch 3/20
329/329 [==============================] - 1s 2ms/step - loss: 7.3106 - mean_squared_error: 7.3106
Epoch 4/20
329/329 [==============================] - 1s 2ms/step - loss: 4.9526 - mean_squared_error: 4.9526
Epoch 5/20
329/329 [==============================] - 1s 2ms/step - loss: 4.3464 - mean_squared_error: 4.3464
Epoch 6/20
329/329 [==============================] - 1s 2ms/step - loss: 5.8193 - mean_squared_error: 5.8193
Epoch 7/20
329/329 [==============================] - 1s 2ms/step - loss: 4.8714 - mean_squared_error: 4.8714
Epoch 8/20
329/329 [==============================] - 1s 2ms/step - loss: 4.8278 - mean_squared_error: 4.8278
Epoch 9/20
329/329 [==============================] - 1s 2ms/step - loss: 3.9817 - mean_squared_error: 3.9817
Epoc

In [66]:
pred_train= model.predict(X_train)
print(np.sqrt(mean_squared_error(y_train,pred_train)))

pred= model.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,pred))) 

0.9134095055619667
0.9317314483714805


### The first line of code predicts on the train data, while the second line prints the RMSE value on the train data. The same is repeated in the third and fourth lines of code which predicts and prints the RMSE value on test data.

In [69]:
pred

array([[133.32233],
       [165.60696],
       [133.24268],
       ...,
       [131.35298],
       [135.0003 ],
       [134.42787]], dtype=float32)

In [70]:
pred_train

array([[133.78947 ],
       [132.41571 ],
       [108.59266 ],
       ...,
       [126.57919 ],
       [133.94077 ],
       [122.370415]], dtype=float32)

### Here we predicted  turbine energy yield (TEY)  using test and train data.